

services:
  app:
    container_name: log-tool
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "514:5140/udp"
    volumes:
      - sqlite_data:/app/prisma
    environment:
      - DATABASE_URL=file:/app/prisma/prod.db
      - NODE_ENV=production
      - JWT_SECRET=your_ultra_secure_secret_change_me

volumes:
  sqlite_data:
